### ISSUE TITLE
Disabling pwmio3 variable may effect PWM prescaler setup for DC Fan

### ISSUE THREAD

**Issue by James-NZ** [greencardigan/TC4-shield#1]
Could you please check if the following commit means that the PWM prescaler is no longer configured when using CONFIG_PWM (DC Fan):
https://github.com/greencardigan/TC4-shield/commit/1a43b605e0eeed1d8f1c8d5bd6899b52d568b04e

As far as I can tell, calling pwmio3.Setup is the only way that the prescaler is configured which is still relevant for analogWrite() as this is equivalent to pwmio3.Out().

Just to be sure, I have changed my fork to : 
#ifndef CONFIG_PAC3
  pwmio3.Setup( IO3_PCORPWM, IO3_PRESCALE_128 ); // setup pwm frequency on IO3
#endif

And used pwmio3.Out() instead of analogWrite() in outIO3() just to be consistent. Refer to this merge:
https://github.com/James-NZ/TC4-shield/commit/e5bec38d448a953b3f53fba392a26abc10d823d0

This commit for bumpless PID transfer may also be of interest:
https://github.com/James-NZ/TC4-shield/commit/82f7914ceee186b2ed3b74054522580cb488c435

Cheers,
James

**Comment by greencardigan** [comment]
Thanks James,
I might forward this to Jim to look at.
Cheers,
Brad

**Comment by greencardigan** [comment]
Hi James,
Does this commit address your issue?
https://github.com/greencardigan/TC4-shield/commit/6602013d9a99aa43e575d62d287cea674e6788f0
