### ISSUE TITLE
Setting up artisan with EMKO TCE

### ISSUE THREAD

**Issue by JugoOriginal** [greencardigan/TC4-shield#13]
Hey,
i am trying to setup a EMKO TCE with an arduino and TC4+ in artisan but i am kind of struggling and i stumbled on your page and you seem to know quite a bit about this topic.
My end goal is to send the measured temperature via WiFi to artisan.
Could you help me out please?
![unnamed](https://github.com/greencardigan/TC4-shield/assets/80098930/81579ce4-b83c-4a52-a0a7-063fd6007b49)
![unnamed](https://github.com/greencardigan/TC4-shield/assets/80098930/aee95d6e-82aa-4cc3-8fcc-2532bdca3da9)

**Comment by JugoOriginal** [comment]
first of all,  thanks for the fast reply!

1. i would like to get the measurements from the sensor into artisan... i never used this before and couldnt get this setup

<img width="651" alt="image" src="https://github.com/greencardigan/TC4-shield/assets/80098930/852a1426-b0d4-4123-bf87-9493a6ca25f1">

2. in the second step, i would like to send the data remotely to artisan.. basically establish a wireless communication... initially i wanted to use wifi but apparently that is not a good idea.

3. does anyone have experience with such a setup or are there anywhere detailed instructions that i can simply follow? which bluetooth device i need to buy, arduino code etc. 

Thank you for your help!

**Comment by renatoa** [comment]
BT module is good, it is known also as HC-05. Tons of resources if you search by this name and Arduino. For example:
https://www.instructables.com/Arduino-Bluetooth-Remote-Control-Part-1-Bluetooth-/

For TC4 the main rsources are hosted here:
https://homeroasters.org/forum/viewforum.php?forum_id=133
Just browse the threads about install and setup.

**Comment by JugoOriginal** [comment]
thank you very much i´ll do my best to figure this out!
