### ISSUE TITLE
I want to modify aArtisanQ_PID_6_2_2.zip and fork this repository to share the code

### ISSUE THREAD

**Issue by TonyHo722** [greencardigan/TC4-shield#2]
Hi greencardigan,
I can't find any licence file in aArtisanQ_PID_6_2_2.zip.
Can I just modify it and fork this repository and share the updated code?

-Tony

**Comment by greencardigan** [comment]
Hi Tony,
The licence details are in the code files. BSD licence. Fork, modify and share is fine. 
Brad
