### ISSUE TITLE
Conflict between CONFIG_PAC2 or CONFIG_PAC2_IO3HTR, and parallel LCD

### ISSUE THREAD

**Issue by timbarnes** [greencardigan/TC4-shield#5]
This issue has been seen with version aArtisanQ_PID 6_3, installed in a genuine Arduino UNO.

Line IO2 is assigned to Arduino D2, and is used to read the ZCD in the case that CONFIG_PAC2 or CONFIG_PAC2_IO3HTR have been selected.

The same Arduino D2 line is used for RS in the configuration of the parallel LCD display. 

The CONFIG_PWM and CONFIG_PAC3 work correctly with the parallel LCD display. 

The result of the conflict is incorrect data being written to the display. 

One tested workaround is to redefine the LCD's RS line to use D5: this removes the conflict and will work in the case that the LCD is hand-wired to the Arduino.

**Comment by greencardigan** [comment]
https://github.com/greencardigan/TC4-shield/commit/6405a10419cd8967fb9f39c79285bbbecf306dd1#diff-f65783eacc8bfbeae78e107c74080bca6f3278866cea066bb1953e1ce67d49c3
