### ISSUE TITLE
PID profile number 

### ISSUE THREAD

**Issue by renatoa** [greencardigan/TC4-shield#6]
Why is the parsed value of profile number incremented by one at the line below?
https://github.com/greencardigan/TC4-shield/blob/master/applications/Artisan/aArtisan_PID/trunk/src/aArtisanQ_PID/cmndreader.cpp#L577
This increment led to strange behavior in my practice... for example if I want to set manual mode, I have to send PID;P;-1 command, which is weird...

Also, I think that profile_number_new variable should be synced with profile_number, because it is used in many places instead.
For example, if the user switch LCD_mode to 1, after a PID;P;x command is issued, will have the screen initialized with former profile_number, instead the new profile_number x, modified by PID;P;x command.

**Comment by greencardigan** [comment]
I don’t recall why I had incremented the profile number. Maybe it was old code prior to adding the PID feature and using profile 0. I will remove the increment.

I think I will sync profile_number and profile_number_new in cmndreader after line 577. That should work? However, most users that are using eeprom profiles and buttons would be in standalone mode and would not be using roasting software or the PID;P command.

**Comment by renatoa** [comment]
Yes, it's ok after 577, same location added in my code too.
