### ISSUE TITLE
Setpoint used instead SV, out of visibility scope

### ISSUE THREAD

**Issue by renatoa** [greencardigan/TC4-shield#7]
Trying today to debug something, activated ACKS_ON, and got the following compile error:

```
sketch\cmndreader.cpp: In member function 'virtual boolean pidCmnd::doCommand(CmndParser*)':
cmndreader.cpp:636:60: error: 'Setpoint' was not declared in this scope
       Serial.print(F("# PID setpoint = ")); Serial.println(Setpoint);

```

...at this line:
https://github.com/greencardigan/TC4-shield/blob/master/applications/Artisan/aArtisan_PID/trunk/src/aArtisanQ_PID/cmndreader.cpp#L614

My guess is that the author intended to print SV, not Setpoint, which is not declared External in cmndreader.cpp
And nobody used ACKS_ON since then :)

**Comment by greencardigan** [comment]
https://github.com/greencardigan/TC4-shield/commit/1af3a99a78ed36d4f7126ab66c72f3f1bc9e5203
