### ISSUE TITLE
Wrong parameter index in PID;P command

### ISSUE THREAD

**Issue by renatoa** [greencardigan/TC4-shield#8]
Please check here:
https://github.com/greencardigan/TC4-shield/blob/master/applications/Artisan/aArtisan_PID/trunk/src/aArtisanQ_PID/cmndreader.cpp#L584

paramStr(1) is not the profile number, but the P command
Should be paramStr(2)

**Comment by greencardigan** [comment]
This command was originally intended to be used as per the documentation PID,Px.

However, I think it makes sense to change it to PID,P,x so it is consistent with the other command formats.

**Comment by greencardigan** [comment]
https://github.com/greencardigan/TC4-shield/commit/1af3a99a78ed36d4f7126ab66c72f3f1bc9e5203
